// #ifndef CONFIG_H
// #define CONFIG_H

// #include <zephyr/autoconf.h>

// // Measurement and advertising intervals and timing
// #define ADVERTISEMENT_INTERVAL CONFIG_ADVERTISEMENT_INTERVAL
// #define BLE_TIMEOUT CONFIG_BLE_TIMEOUT
// #define MEASUREMENTS_PER_INTERVAL CONFIG_MEASUREMENTS_PER_INTERVAL
// #define SENSOR_WARMUP_TIME_MS CONFIG_SENSOR_WARMUP_TIME_MS

// // Bluetooth
// #ifdef CONFIG_ENABLE_CONN_FILTER_LIST
// #define ENABLE_CONN_FILTER_LIST
// #endif
// #define TEMPERATURE_SCALE CONFIG_TEMPERATURE_SCALE
// #define HUMIDITY_SCALE CONFIG_HUMIDITY_SCALE
// #define PRESSURE_SCALE (CONFIG_PRESSURE_SCALE_INT / 10.0f)
// #define CO2_CONCENTRATION_SCALE CONFIG_CO2_CONCENTRATION_SCALE
// #define VOC_INDEX_SCALE CONFIG_VOC_INDEX_SCALE

// // Peripherals
// #ifdef CONFIG_ENABLE_EVENT_LED
// #define ENABLE_EVENT_LED
// #endif
// #ifdef CONFIG_ENABLE_SHT4X
// #define ENABLE_SHT4X
// #endif
// #ifdef CONFIG_ENABLE_SGP40
// #define ENABLE_SGP40
// #endif
// #ifdef CONFIG_ENABLE_SCD4X
// #define ENABLE_SCD4X
// #endif
// #ifdef CONFIG_ENABLE_BMP390
// #define ENABLE_BMP390
// #endif
// #ifdef CONFIG_ENABLE_EPD
// #define ENABLE_EPD
// #endif
// #ifdef CONFIG_ENABLE_BATTERY_MONITOR
// #define ENABLE_BATTERY_MONITOR
// #endif

// // SCD41 configs 
// #define SCD4X_ALTITUDE CONFIG_SCD4X_ALTITUDE
// #define SCD4X_TEMPERATURE_OFFSET CONFIG_SCD4X_TEMPERATURE_OFFSET

// // Battery monitor config
// #define USE_FAST_CHARGING CONFIG_USE_FAST_CHARGING
// #define VOLTAGE_DIVIDER_R1 CONFIG_VOLTAGE_DIVIDER_R1
// #define VOLTAGE_DIVIDER_R2 CONFIG_VOLTAGE_DIVIDER_R2

// #endif